import { Optional } from 'sequelize';

/**
 * User attributes representing the shape of a User record in the database.
 *
 * This is used for type safety when working with User model instances.
 * The id, createdAt, and updatedAt are auto-generated by Sequelize.
 */
export interface IUser {
  id: number;
  username: string;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Interface for creating a new User.
 * id, createdAt, and updatedAt are optional because they're auto-generated.
 */
export interface IUserCreation extends Optional<IUser, 'id' | 'createdAt' | 'updatedAt'> {}